---
title: "Tidy Data"
output: github_document
---

```{r setup}
library(tidyverse)
```

## `pivot_longer`

Load the PULSE data

```{r read_data}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names()
```

Wide format to long format 

```{r pivot_l}
pulse_data_tidy = 
  pulse_data %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit", 
    values_to = "bdi",
    names_prefix = "bdi_score_"
  )
```

Re-write, combine and extend (to add a mutate)
```{r pivot_l_one_step}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit", 
    values_to = "bdi",
    names_prefix = "bdi_score_"
  ) %>% 
  relocate(id, visit) %>% 
  mutate(
    visit = recode(visit, "bl" = "00m")) %>%
  arrange(id, visit)
```

## `pivot_wider`

Make up some data! 

```{r pivot_w}
analysis_result = 
  tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)

analysis_result %>% 
  pivot_wider(
    names_from = "time", 
    values_from = "mean"
  )

```

## `bind_rows`

Read in sub-tables 

```{r read_in_movies}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>% 
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>% 
  mutate(movie = "return_king")

```

Bind all the rows together

```{r bind_movies}
lotr_tidy = 
  bind_rows(fellowship_ring, two_towers, return_king) %>% 
  janitor::clean_names() %>% 
  relocate(movie) %>% 
  pivot_longer(
    female:male, 
    names_to = "gender", 
    values_to = "words"
  ) %>% 
  mutate(race = str_to_lower(race))
```

## Joining datasets 

Import and clean FAS datasets

```{r}
litters_df =  read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  relocate(litter_number) %>% 
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>% 
  mutate(
    wt_gain = gd18_weight - gd0_weight, 
    dose = str_to_lower(dose))


pups_df = read_csv("./data/FAS_pups.csv") %>% 
  janitor::clean_names() %>% 
  mutate(sex = recode(sex, `1` = "male", `2` = "female"))

```

Join FAS data sets

```{r}
fas_df = 
  left_join(pups_df, litters_df, by = "litter_number") %>% 
  arrange(litter_number) %>% 
  relocate(litter_number, dose, day_of_tx)
```

